#! /usr/bin/python

# Declare IDT methods

NUM_IRQ = 48 # change if desired

print """
/* THIS FILE IS AUTOGENERATED, DO NOT MODIFY */
#ifndef __IdtDeclaration_H__
#define __IdtDeclaration_H__

extern "C" {
"""
for i in range(0, NUM_IRQ+1):
    print "extern void intEntry_" + str(i) + "();"

print """
} /* extern "C" */

#endif /* __IdtDeclaration_H__ */
"""
