#!/usr/bin/env awk
#
# versionInfoProc - awk script to process the output of 'bzr version-info'
#
# Copyright (c) 2007 by Filip Brcic
#

BEGIN { 
    FS = ": "
    print "/*"
    print " * Version info header file"
    print " *"
    print " * THIS FILE IS AUTOGENERATED - DO NOT MODIFY AND EXPECT TO KEEP MODIFICATIONS"
    print " */"
    print "#ifndef __BZR_VERSION_H__"
    print "#define __BZR_VERSION_H__"
    print ""
    print "namespace VersionInfo {"
}

END {
    print "}; // namespace VersionInfo"
    print ""
    print "#endif /* __BZR_VERSION_H__ */"
}

/^revision-id/ {
    print "    const char * RevisionID = \"" $2 "\";"
}

/^date/ {
    print "    const char * Date       = \"" $2 "\";"
}

/^build-date/ {
    print "    const char * BuildDate  = \"" $2 "\";"
}

/^revno/ {
    print "    const char * RevisionNo = \"" $2 "\";"
}

/^branch-nick/ {
    print "    const char * BranchNick = \"" $2 "\";"
}

